# Generated by Django 6.0.3 on 2026-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_marks_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
